### PR TITLE
Improve detection of device that contains the NDS ROM

### PR DESCRIPTION
**Pull request by AntonioND**
When accessing the filesystem, what a user normally wants is to access the same drive that holds the NDS ROM being run.

On the DS it is easy. The only available drive is the one of the DLDI driver.

On DSi, it isn't so easy. It is possible to run a ROM that is either on the SD card or in a flashcard (accessed with DLDI).

The easiest way to determine the right drive to use is to use argv[0]. The loader stores the location of the NDS ROM there, including the drive.

The trivial detection should only be used as a fallback mechanism if argv[0] isn't present.

### CODE REVIEW

**Comment by AntonioND** [comment]
@lifehackerhansol I have to test this a bit better, what do you think?

**Comment by AntonioND** [comment]
I've implemented something like this in BlocksDS: https://github.com/blocksds/libnds/commit/91ff8cdb603c65ec8d97a33b53d7cb4e48231ad2

Does it make sense to have the same code here?

**Comment by lifehackerhansol** [comment]
> I've implemented something like this in BlocksDS: [blocksds/libnds@91ff8cd](https://github.com/blocksds/libnds/commit/91ff8cdb603c65ec8d97a33b53d7cb4e48231ad2)
> 
> Does it make sense to have the same code here?

Might need a devkitARM fallback here, since as we know dkP folks won't do anything about it. BlocksDS looks fine.

**Comment by AntonioND** [comment]
Yes, that's fair, but this PR will have to be different anyway, I'm thinking about how to do it.

**Pull request closed without merging**
